# Setup
title: vaguilar
url: https://vaguilar.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Victor Aguilar
  url: https://twitter.com/vaguilar_
  email: victoraguilar90@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about

  - title: Github
    url: https://github.com/vaguilar
